"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
// src/router.ts
var react_router_1 = require("@tanstack/react-router");
var routeTree_gen_1 = require("./routeTree.gen"); // Auto-generated by TanStack Router
exports.router = (0, react_router_1.createRouter)({ routeTree: routeTree_gen_1.routeTree });
