// src/router.ts
import { createRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen'; // Auto-generated by TanStack Router

export const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
